name: "Add info to pull request"

description: "Add test into pull request info"

inputs:
  tacks_numbers:
    description: Task Numbers
    default: "Some default text"
    required: true
  token:
    description: "Github token"
    default: ${{ github.token }}
  pullRequestInfo:
    description: "Text to add in pull request"
    default: "Here is info text"
    # required: true

runs:
  using: node16
  main: index.js